POST http://localhost:8081/api/agenti
Content-Type: application/json

{
  "nome": "Mauricio Bello Due",
  "email": "teste@exemplo.com",
  "tipoAgente": "CLIENTE",
  "archiviato": false
}
###
GET http://localhost:8081/api/agenti/1
###
GET http://localhost:8081/api/agenti
###
GET http://localhost:8081/api/agenti/1/utilizzo-ordini
###
PUT http://localhost:8081/api/agenti/9
Content-Type: application/json

{
  "nome": "Mauricio Bello Atualizado",
  "email": "teste@eXyxemplo.com",
  "tipoAgente": "CLIENTE",
  "archiviato": true
}
###
DELETE http://localhost:8081/api/agenti/11
